#!/usr/bin/env Rscript

# Generate inst/AUTHORS and inst/LICENCE.note for the vendored Rust crates.
#
# This follows the CRAN-oriented pattern used by string2path:
# https://github.com/yutannihilation/string2path/blob/main/update_authors.R
# and the accompanying discussion:
# https://yutani.rbind.io/post/rust-and-cran-repository-policy/
#
# Run from the Rsassy package root:
#   Rscript tools/update-authors.R

root <- normalizePath(".", mustWork = TRUE)
src <- file.path(root, "src")
rust <- file.path(src, "rust")
vendor_tar <- file.path(rust, "vendor.tar.xz")

trim <- function(x) {
  sub("^\\s+", "", sub("\\s+$", "", x))
}

extract_string_value <- function(section, key) {
  idx <- grep(sprintf("^%s\\s*=", key), section)
  if (!length(idx)) {
    return(NA_character_)
  }
  value <- sub("^[^=]*=\\s*", "", section[idx[1]])
  value <- sub("\\s+#.*$", "", value)
  value <- trim(value)
  match <- regexec('^"(.*)"$', value)
  parts <- regmatches(value, match)[[1]]
  if (length(parts) >= 2L) parts[2L] else NA_character_
}

extract_array_value <- function(section, key) {
  idx <- grep(sprintf("^%s\\s*=", key), section)
  if (!length(idx)) {
    return(character())
  }
  value <- sub("^[^=]*=\\s*", "", section[idx[1]])
  j <- idx[1]
  while (!grepl("\\]", value, fixed = FALSE) && j < length(section)) {
    j <- j + 1L
    value <- paste(value, section[j])
  }
  matches <- gregexpr('"([^"\\\\]|\\\\.)*"', value, perl = TRUE)[[1]]
  if (identical(matches, -1L)) {
    return(character())
  }
  raw <- regmatches(value, list(matches))[[1]]
  values <- substring(raw, 2L, nchar(raw) - 1L)
  values <- gsub('\\\\"', '"', values, fixed = FALSE)
  values[nzchar(values)]
}

read_cargo_package <- function(path, vendor_path) {
  lines <- readLines(path, warn = FALSE)
  start <- grep("^\\[package\\]\\s*$", lines)
  if (!length(start)) {
    return(NULL)
  }
  start <- start[1]
  next_section <- grep("^\\[", lines[(start + 1L):length(lines)])
  end <- if (length(next_section)) start + next_section[1L] - 1L else length(lines)
  section <- lines[(start + 1L):end]

  authors <- extract_array_value(section, "authors")
  authors <- trim(gsub("\\s+<[^>]+>", "", authors))
  authors <- authors[nzchar(authors)]

  rel <- sub(paste0("^", normalizePath(vendor_path, mustWork = TRUE), "/?"), "", normalizePath(path, mustWork = TRUE))
  crate_dir <- strsplit(rel, "/", fixed = TRUE)[[1L]][1L]

  list(
    name = extract_string_value(section, "name"),
    version = extract_string_value(section, "version"),
    authors = authors,
    license = extract_string_value(section, "license"),
    repository = extract_string_value(section, "repository"),
    crate_dir = crate_dir
  )
}

find_vendor_path <- function() {
  candidates <- c(file.path(src, "vendor"), file.path(rust, "vendor"))
  for (candidate in candidates) {
    if (dir.exists(candidate)) {
      return(normalizePath(candidate, mustWork = TRUE))
    }
  }

  if (!file.exists(vendor_tar)) {
    stop("Cannot find src/vendor, src/rust/vendor, or src/rust/vendor.tar.xz", call. = FALSE)
  }

  tmp <- tempfile("rsassy-vendor-")
  dir.create(tmp)
  utils::untar(vendor_tar, exdir = tmp)
  vendor_path <- file.path(tmp, "vendor")
  if (!dir.exists(vendor_path)) {
    stop("vendor.tar.xz did not contain a top-level vendor directory", call. = FALSE)
  }
  attr(vendor_path, "cleanup") <- tmp
  vendor_path
}

vendor_path <- find_vendor_path()
on.exit({
  cleanup <- attr(vendor_path, "cleanup")
  if (!is.null(cleanup)) {
    unlink(cleanup, recursive = TRUE, force = TRUE)
  }
}, add = TRUE)

manifests <- list.files(vendor_path, pattern = "Cargo\\.toml$", recursive = TRUE, full.names = TRUE)
packages <- Filter(Negate(is.null), lapply(manifests, read_cargo_package, vendor_path = vendor_path))
packages <- Filter(function(x) !is.na(x$name) && !identical(x$name, "{}"), packages)
packages <- packages[order(vapply(packages, `[[`, character(1), "name"), vapply(packages, `[[`, character(1), "version"))]

format_authors <- function(authors, indent = "  ") {
  if (!length(authors)) {
    return(paste0(indent, "Not listed in Cargo manifest; see bundled crate license files."))
  }
  paste0(indent, authors, collapse = "\n")
}

format_scalar <- function(x) {
  if (is.na(x) || !nzchar(x)) "Not listed in Cargo manifest" else x
}

dir.create(file.path(root, "inst"), showWarnings = FALSE)

writeLines(
  c(
    "Generated by tools/update-authors.R; do not edit by hand.",
    "",
    "The authors of the vendored Rust crates in src/rust/vendor.tar.xz:",
    "",
    unlist(lapply(packages, function(pkg) {
      c(
        sprintf("%s (version %s):", pkg$name, pkg$version),
        format_authors(pkg$authors),
        ""
      )
    }), use.names = FALSE)
  ),
  con = file.path(root, "inst", "AUTHORS")
)

writeLines(
  c(
    "Generated by tools/update-authors.R; do not edit by hand.",
    "",
    "Rsassy bundles and/or builds Rust code as part of the package native library.",
    "For CRAN-style source packages, the vendored Rust crate sources are stored in",
    "src/rust/vendor.tar.xz and are used by Cargo in offline mode during installation.",
    "",
    "This generated notice follows the CRAN-oriented Rust vendoring pattern used by",
    "Hiroaki Yutani's string2path package:",
    "https://github.com/yutannihilation/string2path/blob/main/update_authors.R",
    "and discussed at:",
    "https://yutani.rbind.io/post/rust-and-cran-repository-policy/",
    "",

    "Rsassy package code:",
    "- Copyright: Sounkou Mahamane Toure", 
    "- License: GPL (>= 2), as declared in DESCRIPTION.",
    "",
    "Vendored Rust crate components:",
    ""
  ),
  con = file.path(root, "inst", "LICENCE.note")
)

entry_text <- unlist(lapply(packages, function(pkg) {
  c(
    "------------------------------",
    sprintf("Name:       %s", pkg$name),
    sprintf("Version:    %s", pkg$version),
    sprintf("Files:      vendor/%s/* inside src/rust/vendor.tar.xz", pkg$crate_dir),
    sprintf("Authors:    %s", if (length(pkg$authors)) paste(pkg$authors, collapse = ", ") else "Not listed in Cargo manifest; see bundled crate license files."),
    sprintf("License:    %s", format_scalar(pkg$license)),
    sprintf("Repository: %s", format_scalar(pkg$repository)),
    ""
  )
}), use.names = FALSE)

cat(paste(entry_text, collapse = "\n"), file = file.path(root, "inst", "LICENCE.note"), append = TRUE)
cat("\nThis notice documents bundled third-party components and does not modify the license terms declared for Rsassy itself.\n", file = file.path(root, "inst", "LICENCE.note"), append = TRUE)

message("Wrote inst/AUTHORS and inst/LICENCE.note")
